services:
  - type: web
    name: ec2-password-setup-ui
    env: docker
    plan: free
    dockerContext: poc/ec2-set-ssh-password
    dockerfilePath: poc/ec2-set-ssh-password/Dockerfile
    dockerCommand: npm start
    healthCheckPath: /api/health
    envVars:
      - key: PORT
        value: 3000
